### ISSUE TITLE
Update Streamlink to 2.1.2

### ISSUE THREAD

**Issue by slmnio** [dd-center/obs-streamlink#13]
Streamlink 2.1.2 was just [released](https://github.com/streamlink/streamlink/releases/tag/2.1.2) with many fixes, including some major YouTube fixes - it is broken in this version of obs-streamlink.

**Comment by slmnio** [comment]
I don't have much experience with the Python / C API, but it's probably just importing the right version? 
https://github.com/dd-center/obs-streamlink/blob/1fe5c9c3f118ab2bb6eededaaa06d22756d0fb53/python-streamlink.cpp#L72

As a note, even with the updated streamlink 2.1.2 in my PATH, it won't work. I guess it pulls from some python area somewhere

**Comment by beninswe** [comment]
Easier than that, you just need to upgrade the streamlink via pip in the installation folder.
If you know the commandline, then just run this from the OBS folder:
```
data\obs-plugins\obs-streamlink\Python38\python data\obs-plugins\obs-streamlink\Python38\Scripts\pip.exe install --upgrade streamlink
```
Alternatively, unzip the attached bat file to your OBS folder and double click it.
[update_streamlink.zip](https://github.com/dd-center/obs-streamlink/files/6685373/update_streamlink.zip)

**Comment by Raichard** [comment]
> Easier than that, you just need to upgrade the streamlink via pip in the installation folder.
> If you know the commandline, then just run this from the OBS folder:
> 
> ```
> data\obs-plugins\obs-streamlink\Python38\python data\obs-plugins\obs-streamlink\Python38\Scripts\pip.exe install --upgrade streamlink
> ```
> 
> Alternatively, unzip the attached bat file to your OBS folder and double click it.
> [update_streamlink.zip](https://github.com/dd-center/obs-streamlink/files/6685373/update_streamlink.zip)

I didnt get how you can update it, i just run de bat file in my obs folder and i get nothing :c 
could you please help me? :c

**Comment by cqjjjzr** [comment]
See #17. Check the latest update.
