### ISSUE TITLE
不知道为什么油管不能转播，获取不到分辨率。

### ISSUE THREAD

**Issue by paimengbei** [dd-center/obs-streamlink#14]
不知道为什么油管不能转播，获取不到分辨率。
OBS27.0和24.0版本都试过。obs-streamlink版本是最新的0.2.4
换了好几个梯子，几个节点，挂全局还是直接在高级设置输入HTTP代理都没用，刷新的时候卡一下，然后并没有分辨率选项出现。而且twitch也可以转播，应该不是梯子问题。
试过填B站的直播地址，还有twitch的直播地址可以正常转播，刷新就会出现分辨率。可是油管不行。按刷新没有反应。

**Comment by cqjjjzr** [comment]
See #17. Check the latest update.
