### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by SkYNewZ** [dd-center/obs-streamlink#15]
Paste a Twitch link and click on `refresh definitions` does not work and nothing displayed

**Comment by ColourMans** [comment]
Yes and me too

**Comment by j7j2** [comment]
I confirm. Usting obs 27.0.1, when pasting the link and clicking on "refresh definitions" nothing happens.

**Comment by Landiie** [comment]
@SkYNewZ @ColourMans @VeganTommy [This fixed it for me.](https://github.com/dd-center/obs-streamlink/issues/13#issuecomment-864861086) open a cmd window in admin mode, cd into your obs folder, and run the command

**Comment by cqjjjzr** [comment]
See #17. Check the latest update.
