### ISSUE TITLE
无法转播youtube和twitch的直播

### ISSUE THREAD

**Issue by kokorobeats** [dd-center/obs-streamlink#16]
![01180822](https://user-images.githubusercontent.com/70713712/127767251-e58111ff-1cee-4c73-9e28-a2be4b7bf991.png)
![01181027](https://user-images.githubusercontent.com/70713712/127767252-32ca3d72-0211-4f9b-bdf6-6431ed306a7a.png)
![801180957](https://user-images.githubusercontent.com/70713712/127767254-8cad0331-4f5b-4c01-9fd5-8dec551bf06a.png)
同样的配置，B站的直播正常显示，但是youtube和twitch的直播显示不出来，是哪里出了问题吗？

**Comment by kokorobeats** [comment]
https://github.com/dd-center/obs-streamlink/issues/17
我在这个issues中找到了该插件的最新版本0.2.5版，成功获取到油管直播，请问为什么github这里的版本迟迟没有更新呢？难道你们放弃了github，将项目转移到了其他地方吗？

**Comment by cqjjjzr** [comment]
> #17 我在这个issues中找到了该插件的最新版本0.2.5版，成功获取到油管直播，请问为什么github这里的版本迟迟没有更新呢？难道你们放弃了github，将项目转移到了其他地方吗？

只是忘了在这里更新。。。See #17. Check the latest update.
