### ISSUE TITLE
Info: More recent versions have been released on their Chinese mirror

### ISSUE THREAD

**Issue by dsnvwlmnt** [dd-center/obs-streamlink#17]
I happened to read the Chinese translation of the [Readme](https://github.com/dd-center/obs-streamlink/blob/master/README_zh.md) here and noticed a subtle difference. There's a link to a repo with more recent versions on their Chinese website.

Several new versions in the 2 years since any updates here. Unfortunately no source code, no changelog, and no new options as I had been hoping, but presumably there are improvements.

Latest version here is 0.2.0, over there 0.2.5. They state that users of 0.2.0 should uninstall before install later versions.

https://soft.danmuji.org/obs-streamlink/

**Comment by cqjjjzr** [comment]
Apologize for the inconvenience (just forgot to release on GitHub)

I will soon release a new version.

All recent updates are just updating the embedded Streamlink library.
