### ISSUE TITLE
在下载最新0.2.6版本遇到chrome报病毒

### ISSUE THREAD

**Issue by Jade2121** [dd-center/obs-streamlink#23]
chrome报毒无法下载，换用idm下载后，windows defender 提示执行操作，删除或者隔离。
目前我的解决方法是使用0.2.3版，但还是提示有风险，请问大大这种情况要怎么解决

**Comment by cqjjjzr** [comment]
阿这，应该是误报了……我去WD提交一下误报

应该是可以点进去强行下载下来的，WD 那边可以设置白名单（允许在设备上）

**Comment by cqjjjzr** [comment]
VirusTotal上是没有检测出病毒的：https://www.virustotal.com/gui/file/40e268425c0ffa7b70a531aeddf2e8f2f7c3360832d46a5eba856d00b92fc133?nocache=1

**Comment by Jade2121** [comment]
谢谢大佬回复，又试了一下github版，之前是https://soft.danmuji.org/obs-streamlink/这里下载的。依然是chrome无法下载，会直接删除。
<img width="569" alt="屏幕截图 2022-04-09 071200" src="https://user-images.githubusercontent.com/39907449/162569390-ed58c90c-d2a7-499e-82bc-9270e6501646.png">

**Comment by cqjjjzr** [comment]
这两个是一样的啊。。如果要从 Chrome 下载必须把 WD 的实时检测关了

**Comment by cqjjjzr** [comment]
顺道一提，请问能否给一下 Windows Defender 报告的这个文件是哪种病毒？

**Comment by Jade2121** [comment]
Trojan:Win32/Spursint.F!cl

**Comment by cqjjjzr** [comment]
怪了，我这边上传到Windows Defender的报告单上显示的是没有问题啊

![image](https://user-images.githubusercontent.com/6622592/162601855-13e56acc-b0c6-45d9-9f2b-95804bbe1952.png)

**Comment by cqjjjzr** [comment]
WD 那边说已经更新了，你看看这个页面里面 Analyst Comments 里面的提示？

https://www.microsoft.com/en-us/wdsi/submission/7080a025-df55-4dd6-a681-10fe623d0cc6

**Comment by Jade2121** [comment]
感谢，现在没问题了
