### ISSUE TITLE
添加直播间链接后刷新分辨率无效

### ISSUE THREAD

**Issue by NormanMises** [dd-center/obs-streamlink#25]
大佬 我在国内 想通过streamlink录制**chaturbate**的直播 
由于无法直连 我是打开了clash for Windows来连接
最开始命令行操作时 它总是显示SSL error 我查询得知是python的库未设置代理的问题
我不太会弄代理设置，后来是通过添加`--http-no-ssl-verify`这个参数来解决的这个问题
我把这个参数添加到了streamlink的config文件中 以后就可以链接视频成功了
![image](https://user-images.githubusercontent.com/38835726/164967319-1261da68-1b31-4173-9cfd-67d56a1841b4.png)

但是当我安装obs-streamlink插件后 我在obs中添加一个源后 点击`刷新分辨率列表`之后没有反应 **请问这是怎么回事？如何才能解决呢？**
![image](https://user-images.githubusercontent.com/38835726/164967410-5c1ca1eb-506e-4657-b0e3-2d9abf4a15ca.png)
另外我注意到您的截图中是填写了高级设置中的**http代理**和**https代理**的，可以说明一下**怎么填这个代理的地址吗**？
![image](https://user-images.githubusercontent.com/38835726/164967601-4b330155-13f4-44b2-b64c-517baed4ef1f.png)

**Comment by cqjjjzr** [comment]
如果只是要录制，应该不需要用 obs-streamlink，直接用 streamlink 就可以录啊（

然后 obs-streamlink 用的是一个装在 OBS 安装目录里的独立的 Streamlink 安装，我不知道你的设置会不会在里面生效

我这里配置的代理就是普通的 HTTP/SOCKS5 代理，Clash 应当有相应的配置方法，你可以自行找一下如何配置，同时 Streamlink 的文档关于这两个参数的介绍在 https://streamlink.github.io/cli.html#proxy-support ，且通常情况下你需要把两个参数设置成相同的

**Comment by NormanMises** [comment]
我觉得命令行无法保存每个主播 比较麻烦 另外obs我安装了自动分段的插件比较方便 所以希望都弄到obs里操作

我之前安装的streamlink的config文件是在C盘的`C:\Users\NormanMises\AppData\Roaming\streamlink`里。插件里的Streamlink的config在哪里呢？

我刚才测试了插件对于YouTube的使用是正常的 但chaturbate就不行

**Comment by cqjjjzr** [comment]
插件是通过 API 调用 Streamlink 的，因此未必是走的 config，我记得新版加了自定义 streamlink 参数功能，考虑把你要配置的东西加到里面。

**Comment by NormanMises** [comment]
请问怎么自定义参数呢？直接在locale文件夹里创建config文件吗？

**Comment by cqjjjzr** [comment]
麻了

不知道为什么加的那个 custom_options 没有显示出来，我修一下

**Comment by NormanMises** [comment]
hhh我也是刚发现ini文件里有那个参数

**Comment by cqjjjzr** [comment]
![image](https://user-images.githubusercontent.com/6622592/164971309-b2cefe67-3735-49eb-8420-27df4ef0e1ea.png)

试试发的0.3.0版

**Comment by NormanMises** [comment]
我添加了这个参数`{"http-no-ssl-verify":true, "plugin-dirs":"D:\Apps\Streamlink\pkgs\streamlink\plugins"}`但依然不起作用
不进行ssl认证 和加载我本地的插件

而且不填http代理的话YouTube也是可以用的 但CB依然不行 头大

**Comment by NormanMises** [comment]
奇怪的是twitch也是可以用的 似乎只有streamlink新版不支持的几个nsfw网站用不了 但是我明明添加了参数来使用我本地的nsfw网站的插件

**Comment by NormanMises** [comment]
感觉可能是obs里的这个streamlink的问题

**Comment by cqjjjzr** [comment]
`plugin-dirs` 极有可能在 Streamlink API 使用方式下是不可用的

**Comment by NormanMises** [comment]
那可以把这些streamlink插件也预置进obs插件吗 
https://github.com/Damianonymous/streamlink-plugins

**Comment by cqjjjzr** [comment]
直接把第三方的放进去不太可行，但是你可以修改你自己电脑上的 OBSS，找到 `C:\Program Files\obs-studio\data\obs-plugins\obs-streamlink\Python38\Lib\site-packages\streamlink\plugins`  （或类似的地方）放进去就行了

**Comment by NormanMises** [comment]
成功了！！！感谢老哥！！！（这个文件夹藏得太深了我之前想找这个插件文件夹都找不到）
建议老哥把这个文件夹注明在GitHub的md上呢
