### ISSUE TITLE
有时候点击更新分辨率没有反应，打开眼睛也没有反应。有时重启电脑可解决

### ISSUE THREAD

**Issue by lxq690971923** [dd-center/obs-streamlink#26]
版本：3.0

**Comment by cqjjjzr** [comment]
可能是网络问题，你有配置好代理吗？

另外一般不需要重启电脑，直接重启 OBS 或者反复点几下眼睛就可以了

**Comment by lxq690971923** [comment]
你好，打开YouTube等网站是没有问题的。重启OBS、更换节点也没有解决。刷新分辨率列表没有反应 具体是指：点击后没有跳出best等字样列表也是空的。感谢回复

**Comment by cqjjjzr** [comment]
配置代理指的是在插件内部的 http 代理、https 代理里配置好本地的代理的 URL。

你可以考虑发一下 OBS 的日志（帮助-日志文件-查看日志文件），把最新的几个打包发上来

**Comment by lxq690971923** [comment]
原来是这样😢，之前没有填那两个空位也可以连上（请问一下本地的代理的 URL一般是在哪里看呢？

**Comment by cqjjjzr** [comment]
取决于你用的代理客户端种类了，SS/SSR一般两个空都填 `http://localhost:1080`，clash之类的我就不清楚了，可以看看客户端上有没有明确标出 HTTP 或 SOCKS5 代理的端口

**Comment by lxq690971923** [comment]
好的非常感谢！端口写着7890的话要怎么填呢？http://127.0.0.1:7890吗？

**Comment by cqjjjzr** [comment]
如果是 HTTP 协议，那就是。

**Comment by lxq690971923** [comment]
非常感谢！！！！解决了！！！谢谢辛苦了！

**Comment by lxq690971923** [comment]
非常感谢！！！！解决了！！！谢谢辛苦了！
