### ISSUE TITLE
[非常严重的问题] 拉流断断续续

### ISSUE THREAD

**Issue by NormanMises** [dd-center/obs-streamlink#27]
#20 与这个问题相同 使用obs插件时拉非大陆流时断断续续**非常严重** 有时能卡很长时间 已经**严重**影响了使用 请作者大佬尽快查看一下

**Comment by cqjjjzr** [comment]
考虑加大几个buffer size（至少可以加大环形缓冲，不知道你拉的流是不是 HLS 的，如果不是 HLS，那两个 HLS 参数就没用），加上检查梯子的质量。我这边用比较好的梯子转播 YouTube 还算流畅啊……

目前用来播放流的 media-playback 对网络波动不太耐受，但是我暂时还没有时间去换别的方案。您有时间的话可以看看有没有别的方案可以嵌入 OBS（libvlc 似乎也不太行，API 不是特别友好）

**Comment by NormanMises** [comment]
嗯嗯 我缓冲一般都写的32
可以检查一下chaturbate这个网站的流是不是HLS吗？
eg. [chaturbate](https://chaturbate.com/aisneon/)
media-playback是指的是win自带的Windows Media Player吗？我是WIN11最新版的
谢谢！

**Comment by cqjjjzr** [comment]
不是，media-playback 是 OBS 自带的媒体源的，用 FFmpeg 进行播放的内核，里面处理网络波动的处理比较弱

看了下那个 plugin，就是用的 HLS，那可以考虑 两个 HLS 参数（确保你知道你改的参数是啥意思，可以去 Streamlink 的官网看这些参数的意义）

**Comment by NormanMises** [comment]
那可以手动下载FFmpeg进行更新吗？

**Comment by cqjjjzr** [comment]
不能，有问题的是 **调用 FFmpeg** 的代码，我是从 OBS 拉的最新代码，就已经这样了

我目前想的是看看 libmpv，要么就在现有 mp 的基础上改，但说真的你或许应该换个好点的梯子（

**Comment by NormanMises** [comment]
好的谢谢~ 唉 可怜的局域网（
