### ISSUE TITLE
OBS更新至28.0.1后插件不兼容

### ISSUE THREAD

**Issue by AkiZZZZZ** [dd-center/obs-streamlink#29]
更新到28.0.1后插件直接无法添加（点＋后的列表里没有StreamlinkSource），回退至27.2.4版本则可正常使用。

**Comment by cqjjjzr** [comment]
近期暂时没有时间看，请问您能去日志（帮助-日志文件-查看当前日志），把安装插件但没法添加后的日志原文发一下吗？

**Comment by cqjjjzr** [comment]
Closed via https://github.com/dd-center/obs-streamlink/releases/tag/0.4.0
