### ISSUE TITLE
没有可用的属性

### ISSUE THREAD

**Issue by simonxiao86** [dd-center/obs-streamlink#3]
![image](https://user-images.githubusercontent.com/11852705/83534746-d1c4de80-a523-11ea-9852-c1b48f604d9d.png)
添加streamlinksource源之后，打开属性时一片空白
日志：13:19:36.506: [Streamlink Source 'StreamlinkSource']: Error initializing streamlink session: Unknown exception
13:19:36.507: Failed to create source 'StreamlinkSource'!

**Comment by cqjjjzr** [comment]
请问有无更多的日志，或先尝试更新到最新版本？

**Comment by cqjjjzr** [comment]
close due to inactivity

同时您可能需要看看是不是用到了别的使用 Python 3.8 的脚本，可能有冲突
