### ISSUE TITLE
Installed obs and obs-streamlink several times, there is no StreamlinkSource

### ISSUE THREAD

**Issue by nazoren** [dd-center/obs-streamlink#30]
Hello,
I download the installer from the [latest release](https://github.com/dd-center/obs-streamlink/releases/latest) and run it.
Doubled checked everything, all is same as described in your read me page:
https://github.com/dd-center/obs-streamlink#readme

Unfortunately there is no StreamlinkSource to add as a scene.
I tested the same with vlc and several other programs and plugins they all work.
I really appreciate your help. 
Ideally I want to use our main Youtube Video live stream (in English) to playback in my OBS to translate to Turkish live to stream back to Youtube again. 
have been using the browser source but I dont want to use the browser source anymore and your plugin looks awesome but can not make it work.
I'm w'll'nmg to pay/donate some to help your cause as well.
Log file is below:
https://obsproject.com/logs/mmKNa_rdUEFxVvLL

Thank you very much

It is a brand new laptop, HP 669A1UA#ABA

Processor	12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
Installed RAM	16.0 GB (15.7 GB usable)

 
 General specifications 
Operating system 
Windows 11 Home 64-bit Version: 22000.856 

Microprocessor 
12th Gen Intel(R) Core(TM) i7-12700H 

System memory 
16 GB 

Memory slot 1 
8GB SK Hynix 3200MHz 
Memory slot 2 
8GB SK Hynix 3200MHz 

System board 
891C 63.33 

System BIOS 
F.05 

Video 
Graphic device 1 
Intel(R) Iris(R) Xe Graphics 

Current resolution 
3072 x 1920 

Refresh rate 
60 Hz 

Version 
30.0.101.1934 (4/20/2022)

**Comment by cqjjjzr** [comment]
duplicate #29 .

**Comment by cqjjjzr** [comment]
Sorry that I'm pretty busy these days so I can't upgrade the plugin to support OBS 28 for now. Can you consider downgrade the OBS version to OBS 27.x?

**Comment by nazoren** [comment]
Thank you for your fast reply, I can definitely try 27.x since I'll use
only this feature to translate a YouTube live stream...
Will test and let you knowz thanks again

**Comment by cqjjjzr** [comment]
closed due to duplication.
