### ISSUE TITLE
OBS更新至28.0.3后插件不显示

### ISSUE THREAD

**Issue by CYCLC** [dd-center/obs-streamlink#32]
跟28.0.1一样，请问可以更新吗? 28.0更新了AMD的直播画质所以比较需要

**Comment by cqjjjzr** [comment]
最开始我想的是把整个FFmpeg依赖变成动态链接，这样就不会出现这次这样升级OBS大版本就炸掉FFMpeg依赖。似乎FFmpeg变大版本也会炸依赖，因此这样做是不可行的，后续再考虑办法吧（比如把FFmpeg带在插件里……？）

因为是重复的issue，先关了。讨论移步 #29
