### ISSUE TITLE
Any plans to update this for v28

### ISSUE THREAD

**Issue by TBO1981** [dd-center/obs-streamlink#33]
as the title says Any plans to update this for v28, would love to use this for various reasons, just a question, not pushing or complains

**Comment by tnbhaeufi** [comment]
bump

**Comment by cqjjjzr** [comment]
Trying to build OBS28 currently, but I'm still busy these times, so it may cost more time...

**Comment by tnbhaeufi** [comment]
> Trying to build OBS28 currently, but I'm still busy these times, so it may cost more time...

Thanks for your work! Being busy is ok! Maybe drop some info that it´s been worked on in README to let people know this repo isn´t stalled.

**Comment by TBO1981** [comment]
good to hear, btw not complaining, I just know many were wondering, keep up the great work well you can, I've just been using both 27 and 28 for different things

**Comment by cqjjjzr** [comment]
closed via https://github.com/dd-center/obs-streamlink/releases/tag/0.4.0
