### ISSUE TITLE
添加插件后无法选择清晰度也没有画面

### ISSUE THREAD

**Issue by kimoou9** [dd-center/obs-streamlink#35]
日志报告
03:16:34.756: [Streamlink Source]: Failed to open streamlink stream for URL https://www.youtube.com/watch?v=ECQG2u0OID8! PluginError('Unable to open URL: https://www.youtube.com/watch?v=ECQG2u0OID8 (429 Client Error: Too Many Requests for url: https://www.google.com/sorry/index?continue=https://www.youtube.com/watch%3Fv%3DECQG2u0OID8&q=EhAkAIkCAAAAAPA8k__-ovQvGJTQ8Z0GIjCCLyoQCiZlDDrwp61K2lSc4WEhr7wk_6hxyZ7O2cytrL3C2BW_Tlhb70l3btcoZLcyAXI)')
请问这该如何解决

**Comment by cqjjjzr** [comment]
字面意思，被服务器throttle了，用的梯子可能不太干净

**Comment by kimoou9** [comment]
> 

我明白了！感谢🙇‍
