### ISSUE TITLE
点击“刷新分辨率列表”后没有任何变化

### ISSUE THREAD

**Issue by UnspokenSpell** [dd-center/obs-streamlink#36]
### 操作复现

<img width="865" alt="2023-01-23_04-41-56" src="https://user-images.githubusercontent.com/73733485/213939347-5d60d77a-6c6c-495a-b9c3-16332654200e.png">
1.用 youtube-dl 获得YouTube直播流地址

<img width="161" alt="2023-01-23_04-42-04" src="https://user-images.githubusercontent.com/73733485/213939351-994297ad-726c-4ca3-b4b2-a8ad849bfb8c.png">
2.粘贴地址后，点击“刷新分辨率列表”。
然后没有任何变化，选项没有更新

### 关于环境

操作系统：Win10 专业版
OBS版本：28.0.3
网络：已用Clash代理。开启了虚拟网卡，接管所有流量。
可以用播放器播放链接，但obs-streamlink无反应。

**Comment by cqjjjzr** [comment]
那个 直播间地址 就是直接用来填www.youtube.com/watch?xxxxxxxxxxxxxxxxxx这样的格式的URL的，不是用来填解析后的地址的……

**Comment by UnspokenSpell** [comment]
> 那个 直播间地址 就是直接用来填www.youtube.com/watch?xxxxxxxxxxxxxxxxxx这样的格式的URL的，不是用来填解析后的地址的……


![IMG_20230123_102743.jpg](https://user-images.githubusercontent.com/73733485/213956364-bc5e45ef-f6f5-4e21-ae18-5d0efa9b8fcc.jpg)

换成直播间地址，可以解析bilibil，但YouTube的情况依旧。

**Comment by cqjjjzr** [comment]
那就看看日志吧

**Comment by xfrqh** [comment]
> 址

请问日志路径是？

**Comment by UnspokenSpell** [comment]
> 那就看看日志吧

请问日志路径是？

**Comment by cqjjjzr** [comment]
帮助-日志文件-查看当前日志

**Comment by UnspokenSpell** [comment]
### 日志中出现了这样的日志

> 21:02:55.679: [Streamlink Source 'StreamlinkSource']: Error fetching stream definitions for URL https://www.youtube.com/watch?v=YOsbg4pX8FE: PluginError("Unable to open URL: https://www.youtube.com/watch?v=YOsbg4pX8FE (HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?v=YOsbg4pX8FE (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))))")
>
>21:15:26.408: [Streamlink Source]: Failed to open streamlink stream for URL https://www.youtube.com/watch?v=YOsbg4pX8FE! PluginError("Unable to open URL: https://www.youtube.com/watch?v=YOsbg4pX8FE (HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: /watch?v=YOsbg4pX8FE (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error'))))")


### 我开了代理，也填写了代理地址。但未能解决这个问题。

<img width="398" alt="2023-01-23_21-16-01" src="https://user-images.githubusercontent.com/73733485/214051734-f0ae8db3-e07e-401f-93af-9172eb6d2642.png">

<img width="637" alt="2023-01-23_21-33-07" src="https://user-images.githubusercontent.com/73733485/214052472-67191665-30e2-4992-9edd-57499291bead.png">

**Comment by cqjjjzr** [comment]
呃，代理的格式是 http://123.123.123.123:12345 得加上前缀，文档里有写

**Comment by UnspokenSpell** [comment]
![image](https://user-images.githubusercontent.com/73733485/214054644-b742a559-ed10-4baf-8354-0c5c5e40c410.png)

加上前缀后，问题解决。
