### ISSUE TITLE
Add Streamlink --http-header parameter to settings

### ISSUE THREAD

**Issue by robertdigital** [dd-center/obs-streamlink#8]
Hi,

Some feeds require passing in --http-header to Streamlink.  How can this parameter be passed to Streamlink via obs-streamlink?

Example:

streamlink -l debug --http-header "User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" https://www.earthcam.com/usa/virginislands/stthomas/?cam=stthomas
 
vs

streamlink -l debug https://www.earthcam.com/usa/virginislands/stthomas/?cam=stthomas

Thanks

**Comment by cqjjjzr** [comment]
Can already be done via custom options JSON, closing.
